version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=henaknowledgedb
    ports:
      - "3307:3306"
    volumes:
      - data-volume:/var/lib/mysql

  springboot-docker-container:
    image: shaaarplegs/henaknowledge:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/henaknowledgedb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone

  springbootchatapp-docker-container:
    image: shaaarplegs/henaknowledgechatapp:latest
    ports:
      - "3050:3050"
    build:
      context: "./"
      dockerfile: "DockerfileChat"


volumes:
  data-volume:

